//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eregistation
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> Batch_Id { get; set; }
        public Nullable<int> Salary_Id { get; set; }
        public Nullable<int> TelNo { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
    
        public virtual batch batch { get; set; }
        public virtual SalaryD SalaryD { get; set; }
    }
}
